#Supabase Configuration
SUPABASE_URL = "https://rsqovnieagpqyrqzquhj.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzcW92bmllYWdwcXlycXpxdWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxODc3NDgsImV4cCI6MjA3NTc2Mzc0OH0.vMJa-xcfw56GjOhNG-4e7Vy9YKaWn74HiquLmKVvFDA"
STORAGE_BUCKET = "network-files"









#SUPABASE_URL="https://kmjrnfskswctcyftjwxn.supabase.co"
#SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttanJuZnNrc3djdGN5ZnRqd3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTg3MTMsImV4cCI6MjA3NDk3NDcxM30.0YcG77TVo2UA4H8LgqKHZXJDIcyN4utNtQQLR0ZNQn8"
#STORAGE_BUCKET = "network-files"

