# Supabase Configuration
SUPABASE_URL = "https://rsqovnieagpqyrqzquhj.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzcW92bmllYWdwcXlycXpxdWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxODc3NDgsImV4cCI6MjA3NTc2Mzc0OH0.vMJa-xcfw56GjOhNG-4e7Vy9YKaWn74HiquLmKVvFDA"